print("=== KATA-KATA GALAU ===")
print("Katanya cinta itu buta, tapi kenapa yang sakit hati harus aku? 💔")
print("Dulu chat selalu dibales cepat, sekarang read aja nunggu 3 hari.")
print("Move on itu gampang, yang susah nge-delete kenangan di galeri.")
print("Aku bukan baper, aku cuma terlalu memahami situasi... yang nggak ada.")
print("Kadang aku kangen bukan sama orangnya, tapi sama waktu semua masih baik-baik aja.")
print("Semua lagu tiba-tiba jadi 'lagu kita' pas lagi galau.")
print()
print("Status: Galau akut. Segera hubungi playlist 'Sad Songs' terdekat. 🎧")
print()
print()
print()
print("=== GALAU PASCA PUTUS TAPI KOK SUKA ORANG BARU ===")
print("Baru juga seminggu putus, kok udah mikirin senyum orang lain ya?")
print("Katanya masih sakit hati, tapi kenapa deg-degan liat notif dari dia?")
print("Aku pikir aku butuh waktu buat sendiri, eh malah ketemu distraksi baru.")
print("Ini move on beneran apa cuma pelarian? Bingung sendiri jujur.")
print("Rasanya bersalah suka orang baru padahal luka lama belum kering.")
print("Tapi kok ya... rasanya lebih ringan pas mikirin dia dibanding mikirin mantan.")
print()
print("Kesimpulan: Hati emang aneh, nggak nunggu 'siap' buat mulai suka lagi. 🌱")